Add Manufacturer and change some Fields in Place as blank=True
aborilov/easyproduction pull request #2
Opened 2017-01-08 23:12 UTC by Vonuki

2017-01-12 21:24 UTC, ggevorg reviewed
Need check on None value in methods __str__

2017-01-12 21:24 UTC, ggevorg commented on benteler/models.py
> +        return "{}-{}".format(self.parent_place.name, self.name)
parent_place may be None

2017-01-12 21:24 UTC, ggevorg commented on benteler/models.py
> +        return "{}-{}".format(self.parent.name, self.name)
parent may be None

2017-01-12 21:28 UTC, aborilov requested changes
pls fix

2017-01-12 21:45 UTC, aborilov requested changes

2017-01-12 21:45 UTC, aborilov commented on benteler/models.py
> +    cost_center = models.ForeignKey(CostCenter, on_delete=models.CASCADE, verbose_name=_('CostCenter'), blank=True, null=True )
line too long. 80 chars max

2017-01-12 22:04 UTC, aborilov commented on benteler/models.py
> +                                    blank=True, null=True )
no need for space before the bracket

2017-01-12 22:07 UTC, aborilov commented
@Vonuki you should get rid of those extra "Merge branch..." commit.
you should use rebase instead of merge

2017-01-15 14:41 UTC, aborilov commented on benteler/models.py
> +            return "{}-{}".format(self.parent_place.name, self.name)
why do we need this at all?
where can such name be helpful?
I don't like it

2017-01-15 14:49 UTC, aborilov commented on benteler/models.py
> +        if self.parent.name is None:
it won't work anyway, because `None` is `parent` not it's `name` field

2017-01-15 15:55 UTC, aborilov commented on benteler/models.py
> +    worktime = models.IntegerField(verbose_name=_('WorkTime'))
Why int? what is really mean?

2017-01-15 16:00 UTC, aborilov commented on benteler/models.py
> +    worktime = models.IntegerField(verbose_name=_('WorkTime'))
I think `DurationField` much better suit for this purpose.

2017-01-15 16:07 UTC, aborilov commented
too many changes needed, we understand what we need to change and will do it by self

2017-01-15 16:07 UTC, closed without merging